{
 "title": "Sample Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "container_cpu_utilized",
   "type": "timeseries",
   "description": "container_cpu_utilized",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "container_cpu_utilized{aws_ecs_cluster_name=\"api\"}",
     "legendFormat": "{{container_name}} {{container_image_name}}:{{container_image_tag}}"
    }
   ]
  },
  {
   "title": "container_memory_utilized",
   "type": "timeseries",
   "description": "container_memory_utilized",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "container_memory_utilized{aws_ecs_cluster_name=\"api\"}",
     "legendFormat": "{{container_name}} {{container_image_name}}:{{container_image_tag}}"
    }
   ]
  },
  {
   "title": "envoy container_cpu_utilized",
   "type": "timeseries",
   "description": "container_cpu_utilized",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "container_cpu_utilized{aws_ecs_cluster_name=\"api\",container_name=\"envoy\"}",
     "legendFormat": "{{container_name}} - {{aws_ecs_task_family}}"
    }
   ]
  },
  {
   "title": "envoy container_memory_utilized",
   "type": "timeseries",
   "description": "container_cpu_utilized",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "container_memory_utilized{aws_ecs_cluster_name=\"api\",container_name=\"envoy\"}",
     "legendFormat": "{{container_name}} - {{aws_ecs_task_family}}"
    }
   ]
  },
  {
   "title": "network_rate_tx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "container_network_rate_tx{aws_ecs_cluster_name=\"api\"}"
    }
   ]
  },
  {
   "title": "network_rate_rx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "container_network_rate_rx{aws_ecs_cluster_name=\"api\"}"
    }
   ]
  }
 ]
}