receivers:
  otlp:
    protocols:
      grpc:
      http:
exporters:
  logging:
    loglevel: debug

# Deprecated! - https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/jaegerexporter
# Data sources: traces 
#  jaeger:
#    endpoint: jaeger:14250
#    tls:
#      insecure: true

# New Alternative - Jaeger support OTLP directly
# Data sources: traces
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
processors:
  batch:
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging,otlp/jaeger]
      processors: [batch]
    metrics:
      receivers: [otlp]
      exporters: [logging]
      processors: [batch]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]