{
 "title": "Skillsets Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "container_cpu_utilized",
   "type": "timeseries",
   "description": "container_cpu_utilized",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "container_cpu_utilized{aws_ecs_cluster_name=\"api\",container_name=\"skillsets\"} OR container_cpu_utilized{aws_ecs_cluster_name=\"api\",container_name=\"redis\"}",
     "legendFormat": "{{container_name}} {{aws_ecs_task_id}}"
    }
   ]
  },
  {
   "title": "container_memory_utilized",
   "type": "timeseries",
   "description": "container_memory_utilized",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "container_memory_utilized{aws_ecs_cluster_name=\"api\",container_name=\"skillsets\"} OR container_memory_utilized{aws_ecs_cluster_name=\"api\",container_name=\"redis\"}",
     "legendFormat": "{{container_name}} {{aws_ecs_task_id}}"
    }
   ]
  },
  {
   "title": "envoy container_cpu_utilized",
   "type": "timeseries",
   "description": "container_cpu_utilized",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "container_cpu_utilized{aws_ecs_cluster_name=\"api\",container_name=\"envoy\"}",
     "legendFormat": "{{container_name}} - {{aws_ecs_task_id}}"
    }
   ]
  },
  {
   "title": "envoy container_memory_utilized",
   "type": "timeseries",
   "description": "container_cpu_utilized",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "container_memory_utilized{aws_ecs_cluster_name=\"api\",container_name=\"envoy\"}",
     "legendFormat": "{{container_name}} - {{aws_ecs_task_id}}"
    }
   ]
  },
  {
   "title": "Total active connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "envoy_http_http_5000_downstream_cx_active{}",
     "legendFormat": "{{appmesh_virtual_node}}",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Total active requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "envoy_http_http_5000_downstream_rq_active{}",
     "legendFormat": "{{appmesh_virtual_node}}"
    }
   ]
  },
  {
   "title": "Total request / minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "rate(envoy_http_http_5000_downstream_rq_total{}[1m])",
     "legendFormat": "{{appmesh_virtual_node}}"
    }
   ]
  },
  {
   "title": "Total connection / minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "rate(envoy_http_http_5000_downstream_cx_total{}[1m])",
     "legendFormat": "{{appmesh_virtual_node}}"
    }
   ]
  },
  {
   "title": "network_rate_rx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "container_network_rate_rx{aws_ecs_cluster_name=\"api\"}",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "network_rate_tx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "container_network_rate_tx{aws_ecs_cluster_name=\"api\"}",
     "legendFormat": "{{container_name}}"
    }
   ]
  }
 ]
}