receivers:
  prometheus:
    config:
      global:
        scrape_interval: 15s
        scrape_timeout: 10s
      scrape_configs:
      - job_name: "flask-metrics"
        static_configs:
        - targets: [ 0.0.0.0:5000]
  awsecscontainermetrics:
    collection_interval: 10s
processors:
  filter:
    metrics:
      include:
        match_type: regexp
        metric_names:
            - .*memory.reserved
            - .*memory.utilized
            - .*cpu.reserved
            - .*cpu.utilized
            - .*network.rate.rx
            - .*network.rate.tx
            - .*storage.read_bytes
            - .*storage.write_bytes
exporters:              
  awsemf:
    namespace: ECS/ContainerInsights
    log_group_name:  '/aws/ecs/containerinsights/{ClusterName}/performance'
    log_stream_name: '{TaskId}'
    resource_to_telemetry_conversion:
      enabled: true
    dimension_rollup_option: NoDimensionRollup
    metric_declarations:
        - dimensions: [[ClusterName], [ClusterName, TaskDefinitionFamily]]
          metric_name_selectors: 
            - MemoryUtilized 
            - MemoryReserved 
            - CpuUtilized
            - CpuReserved
            - NetworkRxBytes
            - NetworkTxBytes
            - StorageReadBytes
            - StorageWriteBytes
        - dimensions: [[ClusterName], [ClusterName, TaskDefinitionFamily, ContainerName]]
          metric_name_selectors: [container.*]
  prometheusremotewrite:
    endpoint: $AWS_PROMETHEUS_ENDPOINT
    auth:
      authenticator: sigv4auth
    resource_to_telemetry_conversion:
      enabled: true
  logging:
    loglevel: info
extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679
  sigv4auth:
    region: $AWS_REGION
    service: aps
service:
  extensions: [pprof, zpages, health_check, sigv4auth]
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [logging, prometheusremotewrite]
    metrics/ecs:
      receivers: [awsecscontainermetrics]
      processors: [filter]
      exporters: [logging, prometheusremotewrite]