################
## DEPLOYMENT ##
################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  skillsets
spec:
  template:
    spec:
      containers:
      - name:  skillsets
        livenessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10